# Generated by Django 5.2.7 on 2026-04-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('period', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='available_from',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o período passa a ficar visível para usuários.', null=True),
        ),
        migrations.AddField(
            model_name='period',
            name='available_until',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o período deixa de ficar visível para usuários.', null=True),
        ),
    ]
