# Generated by Django 6.0.3 on 2026-03-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email_alter_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='admission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Admissão'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(blank=True, choices=[('GCM', 'Guarda Civil Municipal'), ('GPCM', 'Guarda Patrimonial Civil Municipal')], max_length=5, null=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='registration',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True, verbose_name='Matricula'),
        ),
    ]
