# Generated by Django 5.2.7 on 2026-06-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_loggedinuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='Obrigar troca de senha'),
        ),
    ]
