# Generated by Django 5.2.7 on 2025-10-22 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('date_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date_start'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('vacancies', models.IntegerField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantoes', to='service.period')),
            ],
            options={
                'ordering': ['date', 'time_start'],
                'unique_together': {('period', 'date', 'time_start')},
            },
        ),
        migrations.CreateModel(
            name='RegistrationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('RESERVA', 'Reserva'), ('CANCELADO', 'Cancelado')], default='RESERVA', max_length=10, verbose_name='Status da Vaga')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inscrição')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_plantoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='service.service', verbose_name='Plantão')),
            ],
            options={
                'verbose_name': 'Inscrição em Plantão',
                'verbose_name_plural': 'Inscrições em Plantões',
                'ordering': ['service', 'registration_date'],
                'unique_together': {('service', 'user')},
            },
        ),
    ]
